=== JordanMarr/Perla/perla.templates.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Perla Templates Configuration",
  "description": "Perla Templates Configuration Schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the template"
    },
    "description": {
      "type": "string",
      "description": "The description of the template"
    },
    "author": {
      "type": "string",
      "description": "The author of the template"
    },
    "license": {
      "type": "string",
      "description": "The license of the template"
    },
    "repository": {
      "type": "string",
      "description": "The repository of the template"
    },
    "group": {
      "type": "string",
      "description": "A unique identifier for this set of templates"
    },
    "templates": {
      "type": "array",
      "description": "A list of objects containing information related to the templates",
      "items": {
        "$ref": "#/$defs/templateObject"
      }
    }
  },
  "required": ["name", "author", "license", "group", "templates"],
  "$defs": {
    "templateObject": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "A unique identifier for this template",
          "required": true
        },
        "name": {
          "type": "string",
          "description": "The name of the template",
          "required": true
        },
        "description": {
          "type": "string",
          "description": "The description of the template"
        },
        "shortname": {
          "type": "string",
          "description": "A short name for the template",
          "required": true
        },
        "path": {
          "type": "string",
          "description": "The path to the template relative to the root of the repository",
          "required": true
        }
      },
      "required": ["id", "name", "shortname", "path"]
    }
  }
}

=== JordanMarr/Perla/src/Perla/offline-templates/perla.config.json
{
  "$schema": "https://raw.githubusercontent.com/AngelMunoz/Perla/fs-rework/perla.templates.schema.json",
  "name": "Perla Templates",
  "description": "Official Perla template starters",
  "author": "Perla",
  "license": "MIT",
  "repository": "https://github.com/AngelMunoz/perla-templates",
  "group": "perla.templates",
  "templates": [
    {
      "id": "basic",
      "name": "Basic Template",
      "shortname": "basic",
      "path": "./basic",
      "description": "Just perla.json and index.html, nothing more, nothing less."
    },
    {
      "id": "fable.feliz",
      "name": "Fable Feliz",
      "shortname": "feliz",
      "path": "./fable-feliz",
      "description": "Fable Compiler + Feliz React SPA template"
    },
    {
      "id": "fable.lit",
      "name": "Fable Lit",
      "shortname": "flit",
      "path": "./fable-lit",
      "description": "Fable Compiler + Lit SPA template"
    },
    {
      "id": "fable.sutil",
      "name": "Fable Sutil",
      "shortname": "fsutil",
      "path": "./fable-sutil",
      "description": "Fable Compiler + Sutil F# Framework SPA template"
    },
    {
      "id": "lit.js",
      "name": "Lit Javascript",
      "shortname": "litjs",
      "path": "./lit-js",
      "description": "Lit WebComponent Framework SPA template"
    },
    {
      "id": "preact.jsx",
      "name": "Preact JSX",
      "shortname": "prejsx",
      "path": "./preact-jsx",
      "description": "Preact JSX SPA template"
    },
    {
      "id": "preact.tsx",
      "name": "Preact TSX",
      "shortname": "pretsx",
      "path": "./preact-tsx",
      "description": "Preact TSX SPA template"
    },
    {
      "id": "react.jsx",
      "name": "React Jsx",
      "shortname": "react",
      "path": "./react-jsx",
      "description": "React JSX SPA template"
    },
    {
      "id": "react.tsx",
      "name": "React TSX",
      "shortname": "reacts",
      "path": "./react-tsx",
      "description": "React TSX SPA template"
    },
    {
      "id": "solid.js",
      "name": "Solid JS",
      "shortname": "solid",
      "path": "./solid-js",
      "description": "Solidjs Web SPA template"
    },
    {
      "id": "vue.jsx",
      "name": "VUE JSX",
      "shortname": "vuejsx",
      "path": "./vue-jsx",
      "description": "Vue.js JSX SPA template"
    }
  ]
}
